# Generated by Django 3.0.5 on 2020-06-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('ApellidoPaterno', models.CharField(max_length=40)),
                ('ApellidoMaterno', models.CharField(max_length=40)),
                ('Domicilio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=40)),
                ('Autor', models.CharField(max_length=45)),
                ('Edicion', models.CharField(max_length=45)),
                ('Editorial', models.CharField(max_length=45)),
                ('Fecha', models.DateField()),
                ('NumPaginas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaVenta', models.DateTimeField(auto_now_add=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Cliente')),
                ('Libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
            ],
        ),
    ]
